### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saramoeini20** [sir-kokabi/resources#1]
سلام. وقت بخیر
میخواستم بدونم امکانش هست از این مدلها داخل پروژه ها استفاده کرد؟ لایسنس خاصی نداره؟

**Comment by sir-kokabi** [comment]
سلام.
مخزن اصلی پروژه https://github.com/roshan-research/hazm هست که از لایسنس MIT تبعیت می‌کنه. 
این مخزن هم یک مکان موقت برای مدل‌هاست که از همین لایسنس تبعیت می‌کنه. 
بنابراین بله تحت لایسنس MIT می‌تونید از مدل‌ها استفاده کتید.
